// Code entirely generated by copilot for test sudokus
// Outputs to sudoku.txt


#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

#define N 9

int is_safe(size_t grid[N][N], int row, int col, int num) {
    for (int x = 0; x < N; x++) {
        if (grid[row][x] == num || grid[x][col] == num) {
            return 0;
        }
    }

    int startRow = row - row % 3, startCol = col - col % 3;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            if (grid[i + startRow][j + startCol] == num) {
                return 0;
            }
        }
    }
    return 1;
}

int solve_sudoku(size_t grid[N][N], int row, int col) {
    if (row == N - 1 && col == N) {
        return 1;
    }
    if (col == N) {
        row++;
        col = 0;
    }
    if (grid[row][col] != 0) {
        return solve_sudoku(grid, row, col + 1);
    }
    for (int num = 1; num <= N; num++) {
        if (is_safe(grid, row, col, num)) {
            grid[row][col] = num;
            if (solve_sudoku(grid, row, col + 1)) {
                return 1;
            }
        }
        grid[row][col] = 0;
    }
    return 0;
}

void write_to_file(const char *filename, size_t grid[N][N]) {
    FILE *file = fopen(filename, "a");
    if (file) {
        for (int row = 0; row < N; row++) {
            for (int col = 0; col < N; col++) {
                fprintf(file, "%zu", grid[row][col]);
            }
        }
        fprintf(file, "\n");
        fclose(file);
    } else {
        perror("fopen");
    }
}

void fill_diagonal(size_t grid[N][N]) {
    for (size_t i = 0; i < N; i += 3) {
        for (int j = 0; j < 3; j++) {
            for (int k = 0; k < 3; k++) {
                int num;
                do {
                    num = rand() % 9 + 1;
                } while (!is_safe(grid, i + j, i + k, num));
                grid[i + j][i + k] = num;
            }
        }
    }
}

void generate_sudoku(size_t grid[N][N]) {
    srand(time(0) ^ getpid() ^ (clock() << 16));
    fill_diagonal(grid);
    solve_sudoku(grid, 0, 0);
}

void remove_numbers(size_t grid[N][N], int amount) {
    int count = 0;
    while (count < amount) {
        int row = rand() % N;
        int col = rand() % N;
        if (grid[row][col] != 0) {
            grid[row][col] = 0;
            count++;
        }
    }
}

int main(int argc, char *argv[]) {
    if (!(argc == 2 || argc == 3)) {
        fprintf(stderr, "Usage: %s <unknown_count> or %s <unknown_count> <sudoku_count>\n", argv[0], argv[0]);
        return 1;
    }

    int amount = atoi(argv[1]);
    if (amount < 0 || amount > N * N) {
        fprintf(stderr, "Amount must be between 0 and %d\n", N * N);
        return 1;
    }

    int amount_to_generate = 1;
    if (argc == 3) {
        amount_to_generate = atoi(argv[2]);
        if (amount_to_generate < 1) {
            fprintf(stderr, "Amount to generate must be greater than 0\n");
            return 1;
        }
    }

    FILE *file = fopen("sudoku.txt", "w");
    if (file) {
        fclose(file);
    } else {
        perror("fopen");
        return 1;
    }
    for (int i = 0; i < amount_to_generate; i++) {
        size_t grid[N][N] = {0};
        generate_sudoku(grid);
        remove_numbers(grid, amount);
        write_to_file("sudoku.txt", grid);
    }
    return 0;
}