// Code entirely generated by copilot for test sudokus
// Outputs to sudoku.txt

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

#define N 9

int is_safe(size_t grid[N][N], int row, int col, int num) {
    for (int x = 0; x < N; x++) {
        if (grid[row][x] == num || grid[x][col] == num) {
            return 0;
        }
    }

    int startRow = row - row % 3, startCol = col - col % 3;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            if (grid[i + startRow][j + startCol] == num) {
                return 0;
            }
        }
    }
    return 1;
}

int generator_solve_sudoku(size_t grid[N][N], int row, int col) {
    if (row == N - 1 && col == N) {
        return 1;
    }
    if (col == N) {
        row++;
        col = 0;
    }
    if (grid[row][col] != 0) {
        return generator_solve_sudoku(grid, row, col + 1);
    }
    for (int num = 1; num <= N; num++) {
        if (is_safe(grid, row, col, num)) {
            grid[row][col] = num;
            if (generator_solve_sudoku(grid, row, col + 1)) {
                return 1;
            }
        }
        grid[row][col] = 0;
    }
    return 0;
}

void fill_diagonal(size_t grid[N][N]) {
    for (size_t i = 0; i < N; i += 3) {
        for (int j = 0; j < 3; j++) {
            for (int k = 0; k < 3; k++) {
                int num;
                do {
                    num = rand() % 9 + 1;
                } while (!is_safe(grid, i + j, i + k, num));
                grid[i + j][i + k] = num;
            }
        }
    }
}

void generate_sudoku(size_t grid[N][N]) {
    srand(time(0) ^ getpid() ^ (clock() << 16));
    fill_diagonal(grid);
    generator_solve_sudoku(grid, 0, 0);
}

void remove_numbers(size_t grid[N][N], int amount) {
    int count = 0;
    while (count < amount) {
        int row = rand() % N;
        int col = rand() % N;
        if (grid[row][col] != 0) {
            grid[row][col] = 0;
            count++;
        }
    }
}

size_t** load_new_sudoku(const int unknown_count, const int sudoku_count) {
    size_t** sudoku_list = malloc(sudoku_count * sizeof(size_t*));
    if (sudoku_list == NULL) {
        perror("malloc failed");
        return NULL;
    }
    for (int i = 0; i < sudoku_count; i++) {
        size_t* sudoku = calloc(81, sizeof(size_t));
        if (sudoku == NULL) {
            perror("calloc failed");
            free(sudoku_list);
            return NULL;
        }
        size_t grid[N][N] = {0};
        generate_sudoku(grid);
        remove_numbers(grid, unknown_count);
        for (size_t k = 0; k < N; k++) {
            for (size_t j = 0; j < N; j++) {
                if (grid[k][j] == 0) {
                    sudoku[k * N + j] = 9;
                } else {
                    sudoku[k * N + j] = grid[k][j] - 1;
                }
            }
        }
        sudoku_list[i] = sudoku;
    }
    return sudoku_list;
}